"""Template for the vault CLAUDE.md generated by `overlord init`."""

from pathlib import Path

_TEMPLATES_DIR = Path(__file__).resolve().parent / "templates"

VAULT_CLAUDE_MD = (_TEMPLATES_DIR / "vault_claude_md.md").read_text()
